services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cryptodb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # ← ДОБАВЬ ЭТОТ БЛОК
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .

  caddy:
    image: caddy:2-alpine
    ports:
      - "3000:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/usr/share/caddy # твоя папка со статикой
    depends_on:
      - app
    networks:
      - default # используем дефолтную сеть

volumes:
  postgres_data:
